// pages/api/check.js
export default async function handler(req, res) {
  const CLICKUP_TOKEN = process.env.CLICKUP_TOKEN;
    const USER_ID = process.env.USER_ID;
      const TEAM_ID = process.env.TEAM_ID;
        const HOURS_BACK = parseInt(process.env.HOURS_BACK || '2', 10);

          if (!CLICKUP_TOKEN || !USER_ID || !TEAM_ID) {
              return res.status(500).json({ error: 'Missing environment variables' });
                }

                  const since = new Date(Date.now() - HOURS_BACK * 60 * 60 * 1000);
                    const dateGt = since.getTime(); // timestamp en ms

                      const headers = { Authorization: CLICKUP_TOKEN };

                        // 1. Obtener tareas asignadas al usuario, actualizadas recientemente
                          const tasksUrl = `https://api.clickup.com/api/v2/team/${TEAM_ID}/task?assignees[]=${USER_ID}&date_updated_gt=${dateGt}&include_closed=false&subtasks=true`;
                            let tasks;
                              try {
                                  const tasksRes = await fetch(tasksUrl, { headers });
                                      if (!tasksRes.ok) throw new Error(`Tasks error ${tasksRes.status}`);
                                          const tasksData = await tasksRes.json();
                                              tasks = tasksData.tasks || [];
                                                } catch (e) {
                                                    return res.status(500).json({ error: 'Failed to fetch tasks: ' + e.message });
                                                      }

                                                        const results = [];

                                                          for (const task of tasks) {
                                                              const taskId = task.id;
                                                                  const taskName = task.name;
                                                                      const taskUrl = task.url;

                                                                          // Comentarios nuevos
                                                                              const commentsUrl = `https://api.clickup.com/api/v2/task/${taskId}/comment`;
                                                                                  try {
                                                                                        const commentsRes = await fetch(commentsUrl, { headers });
                                                                                              if (commentsRes.ok) {
                                                                                                      const commentsData = await commentsRes.json();
                                                                                                              const recentComments = (commentsData.comments || []).filter(c => {
                                                                                                                        const cDate = new Date(parseInt(c.date));
                                                                                                                                  return cDate > since && String(c.user.id) !== String(USER_ID);
                                                                                                                                          });
                                                                                                                                                  for (const c of recentComments) {
                                                                                                                                                            results.push({
                                                                                                                                                                        taskName,
                                                                                                                                                                                    taskUrl,
                                                                                                                                                                                                type: 'comment',
                                                                                                                                                                                                            who: c.user.username,
                                                                                                                                                                                                                        text: c.comment_text,
                                                                                                                                                                                                                                    date: c.date,
                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                } catch (e) { /* ignorar errores por tarea */ }

                                                                                                                                                                                                                                                                    // Actividad reciente (cambios, menciones)
                                                                                                                                                                                                                                                                        const activityUrl = `https://api.clickup.com/api/v2/task/${taskId}/activity`;
                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                  const actRes = await fetch(activityUrl, { headers });
                                                                                                                                                                                                                                                                                        if (actRes.ok) {
                                                                                                                                                                                                                                                                                                const actData = await actRes.json();
                                                                                                                                                                                                                                                                                                        const recentActivity = (actData.activities || []).filter(a => {
                                                                                                                                                                                                                                                                                                                  const aDate = new Date(parseInt(a.date));
                                                                                                                                                                                                                                                                                                                            return aDate > since && String(a.user_id) !== String(USER_ID);
                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                            for (const a of recentActivity) {
                                                                                                                                                                                                                                                                                                                                                      // Solo algunos tipos relevantes
                                                                                                                                                                                                                                                                                                                                                                const typeMap = {
                                                                                                                                                                                                                                                                                                                                                                            'status_changed': 'Cambio de estado',
                                                                                                                                                                                                                                                                                                                                                                                        'priority_changed': 'Cambio de prioridad',
                                                                                                                                                                                                                                                                                                                                                                                                    'task_assigned': 'Tarea asignada',
                                                                                                                                                                                                                                                                                                                                                                                                                'task_moved': 'Tarea movida',
                                                                                                                                                                                                                                                                                                                                                                                                                            'comment': 'Comentario', // suele venir también en actividad
                                                                                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                                                                                                const typeLabel = typeMap[a.type] || a.type;
                                                                                                                                                                                                                                                                                                                                                                                                                                                          results.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      taskName,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  taskUrl,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type: typeLabel,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          who: a.user?.username || '',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      text: a.after?.status || a.after?.priority || '',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  date: a.date,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } catch (e) { /* ignorar */ }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  res.status(200).json({ results, since: since.toISOString() });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }