import { useState } from 'react';
import Head from 'next/head';

export default function Home() {
  const [data, setData] = useState(null);
    const [loading, setLoading] = useState(false);
      const [error, setError] = useState(null);

        const checkClickUp = async () => {
            setLoading(true);
                setError(null);
                    try {
                          const res = await fetch('/api/check');
                                if (!res.ok) throw new Error('Error ' + res.status);
                                      const json = await res.json();
                                            setData(json);
                                                } catch (e) {
                                                      setError(e.message);
                                                          } finally {
                                                                setLoading(false);
                                                                    }
                                                                      };

                                                                        const formatDate = (ts) => {
                                                                            const d = new Date(parseInt(ts));
                                                                                return d.toLocaleString('es-AR', { dateStyle: 'short', timeStyle: 'short' });
                                                                                  };

                                                                                    return (
                                                                                        <div style={{ maxWidth: 700, margin: '0 auto', padding: 20, fontFamily: 'system-ui' }}>
                                                                                              <Head>
                                                                                                      <title>ClickUp Agent</title>
                                                                                                              <meta name="viewport" content="width=device-width, initial-scale=1" />
                                                                                                                    </Head>
                                                                                                                          <h1>🔔 Agente ClickUp</h1>
                                                                                                                                <p>Revisa novedades de tus tarjetas asignadas en las últimas horas.</p>
                                                                                                                                      <button
                                                                                                                                              onClick={checkClickUp}
                                                                                                                                                      disabled={loading}
                                                                                                                                                              style={{ padding: '12px 24px', fontSize: 16, marginBottom: 20 }}
                                                                                                                                                                    >
                                                                                                                                                                            {loading ? 'Revisando...' : '🔍 Revisar ahora'}
                                                                                                                                                                                  </button>

                                                                                                                                                                                        {error && <p style={{ color: 'red' }}>Error: {error}</p>}

                                                                                                                                                                                              {data && (
                                                                                                                                                                                                      <>
                                                                                                                                                                                                                <p style={{ color: '#555' }}>
                                                                                                                                                                                                                            Buscando cambios desde: {new Date(data.since).toLocaleString('es-AR')}
                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                {data.results.length === 0 ? (
                                                                                                                                                                                                                                                            <div style={{ padding: 20, background: '#e6ffe6', borderRadius: 8 }}>
                                                                                                                                                                                                                                                                          ✅ Sin novedades recientes.
                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                          <h2>📋 Novedades encontradas ({data.results.length})</h2>
                                                                                                                                                                                                                                                                                                                                        {data.results.map((item, i) => (
                                                                                                                                                                                                                                                                                                                                                        <div key={i} style={{
                                                                                                                                                                                                                                                                                                                                                                          border: '1px solid #ddd',
                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: 8,
                                                                                                                                                                                                                                                                                                                                                                                                              padding: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                marginBottom: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                  background: '#fff'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href={item.taskUrl} target="_blank" rel="noopener">{item.taskName}</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span style={{ marginLeft: 8, color: '#888' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [{item.type}]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {item.who && <div>👤 {item.who}</div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {item.text && <div style={{ fontStyle: 'italic', marginTop: 4 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          “{item.text.length > 150 ? item.text.slice(0,150)+'...' : item.text}”
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ fontSize: '0.8em', color: '#aaa', marginTop: 4 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {formatDate(item.date)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }